### ISSUE TITLE
Gracefully handle APNS connection resets and timeouts

### ISSUE THREAD

**Issue by dgilland** [dgilland/pushjack#10]
Currently, these types of errors will throw an uncaught error and will cause a proper `APNSResponse` to not be returned. This can lead to the user not knowing which tokens were successful and which ones failed.

**Comment by kukosk** [comment]
#29

**Comment by kukosk** [comment]
I tried to implement this, and also did some tweaks and fixes here: #29.

**Comment by dgilland** [comment]
@kukosk Thanks again for the PR!

**Comment by kukosk** [comment]
No problem, thank you for the lib, it's really great!
