### ISSUE TITLE
Problems with GCM Session auth 

### ISSUE THREAD

**Issue by bradmontgomery** [dgilland/pushjack#11]
Hi,

I'm trying to use pushjack for an android app's notifications, and I keep getting 401: Unauthorized responses from google. I used [Google's curl command](http://developer.android.com/google/gcm/http.html#checkAPIkey) to check the validity of my API_KEY and my device's registration ID, and I noticed that authorization header was of the form:

    "Authorization: key=api_key"

In `GCMConnection`, [here](https://github.com/dgilland/pushjack/blob/master/pushjack/gcm.py#L118), you set the session auth using a `('key', self.api_key)` tuple. Shouldn't that be set on the session header instead?  e.g.

````python
self.session.headers.update({'Authorization': 'key={0}'.format(self.api_key)})
````

I tried this out with requests directly, and it seems to work. If this looks good to you, I'll make the change and send a PR.

Thanks!

**Comment by dgilland** [comment]
Thanks for spotting this and submitting a PR. It's much appreciated!

I've release this fix as [v1.0.1](https://pypi.python.org/pypi/pushjack/1.0.1) which has been uploaded to PyPI.
