### ISSUE TITLE
Priority GCM

### ISSUE THREAD

**Issue by mjsorribas** [dgilland/pushjack#16]
It's posible add the priority?
The documentation of notifications http://developer.android.com/intl/es/design/patterns/notifications.html include priority: normal or high .
The problem is in android 5.x , the message never  show if  the app is not opened recently.
Sorry for my bad english.

**Comment by dgilland** [comment]
Is "priority" a subfield of "notification"? If so then you can include it in the "notification" dict object.

**Comment by mjsorribas** [comment]
it's  Parameter  in Options  like collapse_key.
https://developers.google.com/cloud-messaging/http-server-ref.

**Comment by dgilland** [comment]
That's not supported currently. A PR that adds this would be accepted though. Otherwise, I can add it next week after the holidays.

**Comment by mjsorribas** [comment]
I'm working in my fork .. check my gcm.py file. I added priority, i'm testing right now.
It's not finished.
This Parameter is for try fix some problems of reception of the message, when you try to send messages to Android 5.x in some phones (like Asus .. never comes).

**Comment by dgilland** [comment]
Any progress on this? Should I wait for your PR or go ahead and implement this myself?

**Comment by dgilland** [comment]
I've added support for GCM `priority` via the `low_priority` keyword argument:

```python
# The default is to send a high priority message.
client.send(registration_id, message)  # low_priority=False

# To send a normal priority message, set low_priority=True.
client.send(registration_id, message, low_priority=True)
```

This mirrors the implementation in the APNS module which also uses a `low_priority=False` keyword argument.

This feature has been release as v1.2.0: https://pypi.python.org/pypi/pushjack/1.2.0

**Comment by mjsorribas** [comment]
My implementation of priority works fine. I try to test yours in the next days.
