### ISSUE TITLE
Raising ValidationError if there is atleast one invalid token present in the list of ids

### ISSUE THREAD

**Issue by babu-upcomer** [dgilland/pushjack#21]
Why would we need to raise the validation error if there is just one invalid id? Couldn't the invalid tokens be safely removed and the push notification is sent for the rest of the devices? The invalid tokens can be returned as res.error_tokens.

**Comment by dgilland** [comment]
Do you mean the validation check at https://github.com/dgilland/pushjack/blob/c85f47c085626fed44d885eadc58b162ddeda45a/pushjack/apns.py#L218 or somewhere else?

That token validation is checking only on the format of the token (https://github.com/dgilland/pushjack/blob/c85f47c085626fed44d885eadc58b162ddeda45a/pushjack/apns.py#L733) which basically just checks that it's valid HEX and has the expected length. It doesn't check whether the token actually exists within the APNS network.

Generally, if a token fails this check, there's something fundamentally wrong with the token (wrong length or contains non-HEX characters). This usually indicates that the token wasn't saved correctly or something modified it to make it unusable.

**Comment by babu-upcomer** [comment]
Yes. https://github.com/dgilland/pushjack/blob/c85f47c085626fed44d885eadc58b162ddeda45a/pushjack/apns.py#L754

Why would the exception to be raised even if there is at-least one invalid token? The invalid tokens can be safely ignored instead of raising exception so that the push notifications are sent to rest of the valid tokens.

**Comment by dgilland** [comment]
It was a design choice. A badly formatted token is something that can be checked before sending so I chose to raise an exception if any of the tokens are invalid. It's similar to validating that a `list` contains all strings and raising an exception vs. silently removing the non-strings from the list.

The client-user can choose to remove the invalid tokens if that is the behavior they want by filtering invalid tokens using that method before sending.

**Comment by babu-upcomer** [comment]
Okay. Closing this now. Thanks for the package and clarifications!
