### ISSUE TITLE
Support for Firebase Cloud Messaging

### ISSUE THREAD

**Issue by Lukas0907** [dgilland/pushjack#24]
Hi,

it would be nice to have support for Firebase Cloud Messaging since it is the successor to GCM. The protocol is compatible, however only improvements will be incorporated into FCM.

> You won’t need to make any server-side protocol changes for the upgrade. The service protocol has not changed. However, note that all new server enhancements will be documented in FCM server documentation.

Source: https://developers.google.com/cloud-messaging/faq

Cheers,

Lukas

**Comment by dgilland** [comment]
Is the difference between GCM and FCM just the URL endpoint? Is the request and response format the same?

**Comment by Lukas0907** [comment]
At the moment, it's the same. I've subclassed pushjack's GCM, changed the URL and could send push notifications. However, in the future I expect FCM to gain new features which would obviously not work with the GCM URL.

**Comment by dgilland** [comment]
I'm fine with including a separate `FCM*` classes . Unfortunately, I'm not sure when I'd have time to work on this. I'd gladly review/accept a PR for this though.

**Comment by anandtripathi5** [comment]
@Lukas0907 can you tell me the FCM url

**Comment by Lukas0907** [comment]
The URL is https://fcm.googleapis.com/fcm/send. You can use a simple adapter:

```python
from pushjack.gcm import GCMClient, GCMResponse

FCM_URL = 'https://fcm.googleapis.com/fcm/send'


class FCMClient(GCMClient):
    url = FCM_URL


class FCMResponse(GCMResponse):
    pass
```

GCM will be deprecated as of April 11, 2019, see also https://developers.google.com/cloud-messaging/faq. At this point the GCM endpoints will be shut down. Until then pushjack must also migrate to FCM.
