### ISSUE TITLE
Collapse-id header parameter for APNs client

### ISSUE THREAD

**Issue by ajohnson388** [dgilland/pushjack#26]
I noticed there is no parameter for specifying a collapse-id when sending push notifications with APNs client. I believe the collapse-id is a new parameter Apple added to the accepted APNs request headers, and hence why I don't see it already in this framework. Are there any plans to support this or could I submit a pull request and add this feature?

Thank you,
Andy

**Comment by dgilland** [comment]
I didn't have any plans to add it but if you want to submit a PR, I'll definitely review it and get it merged in.

**Comment by ajohnson388** [comment]
I overlooked the documentation on the collapse id parameter and how this framework was communicating with APNs. Apple deprecated the API used in this framework last year, and their new API which uses HTTP/2 is the only one that supports the collapse id. So it is not possible to add this feature. Thank you for taking the time to help anyways!
