### ISSUE TITLE
Always receiving APNSTimeoutError (Sandbox)

### ISSUE THREAD

**Issue by jorgej-ramos** [dgilland/pushjack#31]
Hi everyone,

I'm trying to use PushJack to deliver pushes to iOS devices on sandbox environment, but I always receive this message:

```APNSTimeoutError (code=None): Timeout for identifier 0```

Here's the basic code I'm trying to use (all elements on <...> are strings):

```python
client = APNSSandboxClient(certificate=<path>)
res = client.send(<token>, "Example")
client.close()
```

Certificates seems to be ok: I'm testing with Knuff on the other hand and works perfectly.
Any help will be appreciated

**Comment by jorgej-ramos** [comment]
Sorry, I didn't export the certificate key and pusher responds with that error. This issue can be closed

**Comment by Aaimek** [comment]
Can you detail a bit more your fix?

**Comment by jorgej-ramos** [comment]
Wow, so long from this. I guess what happened is that I exported the APS certificate of my keychain without the private key, and that's why it did not work.
