### ISSUE TITLE
APNSInvalidTokenError: 'Invalid token format. Expected 64 character hex string: '

### ISSUE THREAD

**Issue by heykarimoff** [dgilland/pushjack#32]
OS: Linux/Ubuntu 16.04
Python: 3.5

For the last month I am getting this error when sending Push notifications to Apple devices.
iOS device token is more than 64 characters, is that possible? or am I having wrong device token?

**Comment by aakhedr** [comment]
What’s the device token string looking like?

**Comment by zroganovic** [comment]
I have experienced the same thing. Here's the specific token which was rejected.

"404287717c747631442456a20b142abfdae03e66d647c5dde74133c10bd2632da0540da95515f6c3eb8ff92bc2f885c28765d4e12c1c"

It was generated by an iPad running iOS 11.0

Here is the Apple documentation which states that "APNs device tokens are of variable length. Do not hard-code their size."

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html

**Comment by aakhedr** [comment]
You are right! This is obviously happening in rare cases. I didn't encounter such a along device token anytime... @dgilland - please advise on this!?
To make sure we are all on the same page, @zroganovic please confirm this is how you are retrieving the device token in `UIApplicationDelegate`:

        func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {

            var plainDeviceToken = NSString(format: "%@", deviceToken as CVarArg) as String

            plainDeviceToken = plainDeviceToken.description.replacingOccurrences(of: " ", with: "").trimmingCharacters(in: CharacterSet(charactersIn: "<>"))

            // Send to remote server
        }

**Comment by zroganovic** [comment]
@aakhedr 

Yes, we are using the method you mention "didRegisterForRemoteNotificationsWithDeviceToken":

Our code:

- (void)application:(UIApplication )application didRegisterForRemoteNotificationsWithDeviceToken:(NSData )devToken
{
    [[NSNotificationCenter defaultCenter] postNotificationName:NotificationServiceDidChangeAuthorizationStatus
                                                        object:self
                                                      userInfo:@{}];
    
    [Utility writeToDebugFile:@"APNs query is successfull with the Apple server..."];
    // Prepare the Device Token for Registration (remove spaces 3and < >)
    NSString *deviceToken = [[[[devToken description]
                               stringByReplacingOccurrencesOfString:@"<" withString:@""]
                              stringByReplacingOccurrencesOfString:@">" withString:@""]
                             stringByReplacingOccurrencesOfString: @" " withString: @""];
    
    self.settings.APNsToken = deviceToken;
    
    [Utility writeToDebugFileWithFormat:@"DID RECEIVE APNS DEVICE TOKEN: %@", deviceToken];
    
    [Utility savePushToken:deviceToken];
}

**Comment by dgilland** [comment]
I've removed the 64 character restriction and released `v1.4.1` with the fix: https://pypi.org/project/pushjack/1.4.1/

Let me know if you still encounter any issues related to token length.
