### ISSUE TITLE
Slow APNS send

### ISSUE THREAD

**Issue by kukosk** [dgilland/pushjack#34]
I came across a problem while releasing a new version of my website. At the beginning, there was quite a few notifications to be sent, and looking at the db, I found out that the sending is really slow like 1 notification in ~10s.

From a brief investigation I found out there might be an issue with the timeout used for reading the response (which is exactly 10s). When `client.send()` is called, the notification appears on my device immediately, but then the script waits probably for the whole timeout until the notification is deleted from my db. By searching for a while, I found out that apple doesn't send any response back if everything is ok, so that might be a reason why it happens. Some people on the internet say that just lowering the timeout to 0.5s fixes this issue, but that's not a solution I'm looking for. It still would be relatively slow, and it may cause issues if the response is not delivered in time.

Do you think there's anything we can do about this? I will have some time in a couple of days, so I can even look into it and try to help.

My scenario:
I'm running a separate script for sending the push notifications (pseudo code):
```
client = APNSClient(...)
while True:
    notifs = db.notifs(10)
    for notif in notifs:
        client.send(notif.user.tokens, msg, ...)
        # some error handling
        db.remove(notif)
    sleep(1)
```

**Comment by kukosk** [comment]
So I read some more about it and found out that it's actually since the new enhanced apns protocol that apple doesn't send any response on success: https://redth.codes/the-problem-with-apples-push-notification-ser/

**Comment by dgilland** [comment]
If you aren't interested in the errors, you can set the error timeout to 0 to disable waiting for an error response after sending (either with `APNSClient(..., default_error_timeout=0)` or on each send with `client.send(..., error_timeout=0)`).

If you are interested in the errors but are sending the same message to bulk recipients, then getting all the tokens at once and making a single send call would result in only a single blocking error check at the end with non-blocking error checks after each individual send. Whereas, in your example, each `notif` block would have a 10 second wait (the default error timeout) after each send call.

- Intermediate error checks: https://github.com/dgilland/pushjack/blob/c500aadd5c722733f8076e9fbebc68652c745fd7/pushjack/apns.py#L449
- Final error check: https://github.com/dgilland/pushjack/blob/c500aadd5c722733f8076e9fbebc68652c745fd7/pushjack/apns.py#L471

**Comment by kukosk** [comment]
The problem is I would really like to get the errors and am sending different messages. I would like to read the errors because I don't want to drop any notifications, which could happen if I ignore the error. The error would not be written to the socket immediately, and also the socket wouldn't close immediately, so there's a possibility that I would send some additional messages (marking them as sent) before that happens. I also have a failure/success counter so that I'm able to remove failing devices from the db.

There's a nice solution to this problem at the end of the article I linked above. I'm not yet sure how hard would it be to implement in the lib, but I will look into it as soon as I have some time :)

**Comment by kukosk** [comment]
Today I found out that there's a new protocol for push notifications which uses HTTP/2, and sends HTTP 200 as a response to a successful POST request. I will look at pushjack and try to implement it.

**Comment by rockstar64-dev** [comment]
Hi Guys,

Sorry to resurrect this issue, but I wanted to check if there was any progress on this. 

If not, we might be able to jump in and help. It seems like the suggestion before was to migrate over to the HTTP/2 API.

Regards,

David

**Comment by kukosk** [comment]
Hi @rockstar64-dev,

I also started investigating into the HTTP/2 API after finding this issue, not just because the old API was slow, but also because even after waiting 10s after each notification, it's not certain that the notification has been sent successfully. The drawbacks that apple made to save bandwidth really destroyed the API in my opinion.

After looking at how simple the new API is, I realised it will be really easy to write my own lib for it, and as I was also planning on implementing push notifications for Safari, it seemed like a really good idea to write something that also supports it. I also wanted it to be really easy to integrate with existing projects, while also catching all potential corner cases. I'm now using it in production for over 4 months, and it never crashed or failed to send a notification.

Feel free to either use it, or take some parts of the code and update pushjack :)

You can find it here: [pyapns_client](https://github.com/kukosk/pyapns_client)

**Comment by rockstar64-dev** [comment]
Hi @kukosk 

Thank you for that, it's exactly what I need, cheers! 

Thank you for the prompt reply.
