### ISSUE TITLE
Hi! python 3.6 support

### ISSUE THREAD

**Issue by jmgamboa** [dgilland/pushjack#35]
First, awesome api you've started. Quick question. I'm on python 3.6. The documentation/readme doesn't quite say if its supported. Mind elaborating?

**Comment by jmgamboa** [comment]
update: tried it with apns sandbox client on python 3.6. resulted in success

**Comment by dgilland** [comment]
It's supported/tested on 2.7, 3.4, 3.5., 3.6, and 3.7.

**Comment by jmgamboa** [comment]
thanks!
