### ISSUE TITLE
send push notification throwing an error in sandbox environment 

### ISSUE THREAD

**Issue by saiteja59** [dgilland/pushjack#39]
we are able to send push notifications APNSClient environment, but we are getting error while sending push notifications in APNSSandboxClient environment.  Earlier APNSSandboxClient worked for us. From yesterday we are getting error in APNSSandboxClient environment..

client = APNSSandboxClient(certificate=key_path, default_error_timeout=10, default_expiration_offset=2592000, default_batch_size=100, default_retries=5)
token ='341b4205f46aec8ae715f9f7edbd1fa644dc915ad786f33885b82d80a5a16f15'
alert = 'Hello world'
        res = client.send(token,
                        alert,
                        badge='badge count',
                        sound='sound to play',
                        category='category',
                        content_available=True,
                        title='Title',
                        title_loc_key='t_loc_key',
                        title_loc_args='t_loc_args',
                        action_loc_key='a_loc_key',
                        loc_key='loc_key',
                        extra={'custom': 'data'})

We are getting below error:
{'errors': [{'identifier': 0}], 'failures': ['341b4205f46aec8ae715f9f7edbd1fa644dc915ad786f33885b82d80a5a16f15'], 'message': {'action_loc_key': 'a_loc_key', 'badge': 'badge count', 'category': 'category', 'content_available': True, 'extra': {'custom': 'data'}, 'launch_image': None, 'loc_args': None, 'loc_key': 'loc_key', 'max_payload_length': 0, 'message': 'Hello world', 'mutable_content': None, 'sound': 'sound to play', 'thread_id': None, 'title': 'Title', 'title_loc_args': 't_loc_args', 'title_loc_key': 't_loc_key'}, 'successes': [], 'token_errors': {'341b4205f46aec8ae715f9f7edbd1fa644dc915ad786f33885b82d80a5a16f15': {'identifier': 0}}, 'tokens': ['341b4205f46aec8ae715f9f7edbd1fa644dc915ad786f33885b82d80a5a16f15']}

**Comment by dgilland** [comment]
The object returned from `APNSClient.send()` is an `APNSResponse` object which has an `errors` attribute

https://github.com/dgilland/pushjack/blob/b3ac899f025c3318be16756e4e7f3dd34a7a7952/src/pushjack/apns.py#L493
https://github.com/dgilland/pushjack/blob/b3ac899f025c3318be16756e4e7f3dd34a7a7952/src/pushjack/apns.py#L726-L754

that is a list of objects that subclass `NotificationError`.

https://github.com/dgilland/pushjack/blob/b3ac899f025c3318be16756e4e7f3dd34a7a7952/src/pushjack/exceptions.py#L44-L48

Each of those error objects have `code` and `description` attributes which would be able to give you more information about the error (from your code sample, it looks like the errors are being serialized into a dictionary that only contains the `identifier` attribute and not the `code` and `description` attributes).

**Comment by dgilland** [comment]
Removing due to inactivity. Feel free to re-open with additional information.
