### ISSUE TITLE
Notifications not working for iOS 13

### ISSUE THREAD

**Issue by raghavaro** [dgilland/pushjack#44]
With the recent launch of iOS 13, notifications are no longer delivered. 

There is a simple solution. AWS, here, explains how to send notifications to devices on iOS 13 and WatchOS 6.  

https://aws.amazon.com/blogs/messaging-and-targeting/sending-push-notifications-to-ios-13-and-watchos-6-devices/

I'll try to solve this over the weekend, but if anyone in the collaborators want to attempt it before that, please feel free

**Comment by kllr** [comment]
> With the recent launch of iOS 13, notifications are no longer delivered.
> 
> There is a simple solution. AWS, here, explains how to send notifications to devices on iOS 13 and WatchOS 6.
> 
> https://aws.amazon.com/blogs/messaging-and-targeting/sending-push-notifications-to-ios-13-and-watchos-6-devices/
> 
> I'll try to solve this over the weekend, but if anyone in the collaborators want to attempt it before that, please feel free

Hi raghavaro,
 did you manage to get it working? Or is this repo become useless?

**Comment by raghavaro** [comment]
Hi dgilland,

Apple has stopped supporting the API that you used for sending the data to APNS, and therefore it does not support the new apns-priority parameter. 

The push notifications work with the current version of pushjack, but they are unreliable as they can’t support the priority parameter - sometimes it gets delivered late or not at all. 

I couldn’t find the time to switch to the new API, and probably won’t be able to in the near future. Apologies! 
 
Best,
Raghav

**Comment by JonasDeichelmann** [comment]
Hey,

I run in the same trouble than @raghavaro. For our APNS-Service we got the critical-alert entitlement from Apple and it isn't working correctly.

@dgilland are you working on that issue?

Cheers,
Jonas

**Comment by dgilland** [comment]
Unfortunately, the `apns-push-type` header is only supported on the new HTTP/2 APNs Provider API. This library uses the legacy Binary Provider API. So in order to add `apns-push-type` support, the full HTTP/2 Provider API would have to be added.

I don't have plans to personally migrate this library to use the HTTP/2. I don't have the time, and I'm no longer involved in mobile development so it's not something I can prioritize.

So with the Binary Provider API now deprecated and likely to be shutdown later this year, this library will unfortunately also be deprecated.

**Comment by JonasDeichelmann** [comment]
Hi @dgilland ,

thank you for your response. To you have additional recommendations for getting in this topic?
Like tutorials or some articles?
I would start building my own, since I need something like that for my project.

Or do you maybe have a similar API/Library to that?

Cheers,
Jonas

**Comment by dgilland** [comment]
@JonasDeichelmann Looks like someone forked this repo to add an HTTP/2 client: https://github.com/joseph-fox/pushjack. It's also been published to PyPI: https://pypi.org/project/pushjack-http2/.

Then there's other APNs2 libraries like:

- https://github.com/Pr0Ger/PyAPNs2
- https://github.com/genesluder/python-apns
- https://github.com/ofw/apns2-client

@joseph-fox

**Comment by JonasDeichelmann** [comment]
Thank you very much that’s really helpful.
