### ISSUE TITLE
How to close GCMClient?

### ISSUE THREAD

**Issue by q1q1w1w1q** [dgilland/pushjack#46]
Hi,

I got the error below after `client.send(registration_id, message=msg)`.
Is there a way I can close it in the `finally` block?

The logs:
`ResourceWarning: unclosed <ssl.SSLSocket fd=6, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2a02:6b60:d083:0:f46e:d7ac:6724:2d6f', 51262, 0, 0), raddr=('2a00:1450:4009:800::200a', 443, 0, 0)>`

The env:
macOS Catalina 10.15.2

**Comment by dgilland** [comment]
Can close it via the underlying requests session:

```python
client.conn.session.close()
```
